CREATE TABLE `page_content` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `page` varchar(200) COLLATE utf8_unicode_ci NOT NULL,  `paragraph_index` int(11) NOT NULL,  `text` text COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `page_content` VALUES('1', 'vorstand', '1', 'Am 22.05.2018 wurde bei der Mitgliederversammlung im Olympiastützpunkt/Linz der neue Vorstand für die Funktionsperiode 2018-2021 gewählt. Im Vorstand werden wichtige Entscheidungen stets gemeinsam getroffen. Die höchste Instanz ist Präsident Herbert Koch.');
CREATE TABLE `settings` (  `setting` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `value` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`setting`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
CREATE TABLE `users` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `username` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `firstname` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `lastname` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `sex` varchar(10) COLLATE utf8_unicode_ci NOT NULL,  `email` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `password` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `users` VALUES('1', 'TobiHatti', 'Tobias', 'Hattinger', 'M', 'tobias.hattinger@gmx.at', '77e948e99b537a8c3c9056f77702439e2b8275cfbf6e2bc59a8d89fca0e7767f');
CREATE TABLE `vorstand` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `darstellung` varchar(50) COLLATE utf8_unicode_ci NOT NULL,  `name` varchar(100) COLLATE utf8_unicode_ci NOT NULL,  `bereich` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  `email` varchar(150) COLLATE utf8_unicode_ci NOT NULL,  `telefon` varchar(20) COLLATE utf8_unicode_ci NOT NULL,  `foto` varchar(255) COLLATE utf8_unicode_ci NOT NULL,  PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPACT;
INSERT INTO `vorstand` VALUES('4', 'box', 'Kons. Herbert Koch ', 'Präsident ', 'herbert.koch@gmx.at', '0664/2407556', 'herbert_koch.jpg');
INSERT INTO `vorstand` VALUES('5', 'box', 'Peter Zauner ', 'Sportkoordinator\r\nBorg', 'zape@me.com', '0676/841234861', 'peter_zauner.jpg');
INSERT INTO `vorstand` VALUES('6', 'box', 'Klaus Mitterhauser', 'Vizepräsident\r\nRechtsreferent\r\nHomepage ', 'zape@me.com', '0676/841234861', 'klaus_mitterhauser.jpg');
INSERT INTO `vorstand` VALUES('7', 'box', 'Karin Burger ', 'Schriftführerin\r\nNachwuchsranglisten ', 'ooe-badmintonverband@aon.at', '0681/10621408', 'karin_burger.jpg');
INSERT INTO `vorstand` VALUES('8', 'box', 'Anton ‚Toni‘ Aistleitner ', 'Finanzreferent ', 'anton.aistleitner@hotmail.com', '0660/1348822', 'anton_aistleitner.jpg');
INSERT INTO `vorstand` VALUES('9', 'box', 'Stephan Dlapka ', 'Nachwuchsreferent\r\nSchüler ', '', '0699/19211350', 'stephan_dlapka.jpg');
INSERT INTO `vorstand` VALUES('10', 'box', 'Othmar Auberger ', 'Nachwuchsreferent\r\nJugend ', '', '0664/2407556', 'othmar_auberger.jpg');
INSERT INTO `vorstand` VALUES('11', 'box', 'Andreas Rabel ', 'Vizepräsident\r\nLigareferent\r\nOÖMM ', 'rabel.badminton@aon.at', '0676/9433042', 'andreas_rabel.jpg');
INSERT INTO `vorstand` VALUES('12', 'box', 'Mag. Tina Füreder ', 'Schulsportreferentin\r\nAus- und Weiterbildung', 'tina_4720200@hotmail.com', '0650/4720200', 'tina_fuereder.jpg');
INSERT INTO `vorstand` VALUES('13', 'box', 'Peter Krenmayr ', 'Breitensportreferent\r\nHomepage ', 'kre@gmx.at', '0650/3698352', 'peter_krenmayr.jpg');
INSERT INTO `vorstand` VALUES('14', 'box', 'Lukas und Simon Rebhandl ', 'Pressereferenten\r\nHomepage ', 'berichte-ooebv@gmx.at', '0676/9359342', 'lukas-simon_rebhandl.jpg');
INSERT INTO `vorstand` VALUES('15', 'box', 'Harald Starl ', 'Rechnungsprüfer', 'starl@badminton.at', '0676/5117052', 'harald_starl.jpg');
INSERT INTO `vorstand` VALUES('16', 'box', 'Josef Moser ', 'Rechnungsprüfer', 'pepi-moser@gmx.at', '0676/81424577', 'josef_moser.jpg');
INSERT INTO `vorstand` VALUES('17', 'box', 'Dr. Karl Heinz Lahnsteiner ', 'Rechtsausschuss', 'elahn@tele2.at', '06133/5354', 'heinz_lahnsteiner.jpg');
INSERT INTO `vorstand` VALUES('18', 'box', 'Karl Pröll ', 'Rechtsausschuss\r\nRechungsprüfer ', 'proell.karl@aon.at', '0676/814276220', 'karl_proell.jpg');
INSERT INTO `vorstand` VALUES('19', 'box', 'Peter Schwarzmann ', 'Marketing\r\nAus- und Weiterbildung', 'what.defack@gmx.at', '0699/18151253', 'peter_schwarzmann.jpg');
INSERT INTO `vorstand` VALUES('20', 'box', 'Markus Eckersberger ', 'Schiedsrichterreferent\r\nDoppelranglisten\r\nNachwuchsranglisten', 'markus_eckersberger@gmx.at', '0699/11138311', 'markus_eckersberger.jpg');
INSERT INTO `vorstand` VALUES('21', 'list', 'Otmar Auberger ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('22', 'list', 'Stephan Dlapka ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('23', 'list', 'Alexander Mittermayr ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('24', 'list', 'Klaus Niederhuber ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('25', 'list', 'Peter Schwarzmann ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('26', 'list', 'Sepp Retschitzegger ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('27', 'list', 'Hermann Schausberger ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('28', 'list', 'Peter Kickinger ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('29', 'list', 'Dieter Stockinger ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('30', 'list', 'Phillip Stelzmüller ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('31', 'list', 'Fritz Freimüller ', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('32', 'list', 'Daniel Walchshofer', 'Nachwuchsarbeiterkreis', '', '', '');
INSERT INTO `vorstand` VALUES('33', 'list', 'Klaus Mitterhauser ', 'Ligagremium', '', '', '');
INSERT INTO `vorstand` VALUES('34', 'list', 'Hermann Schausberger', 'Ligagremium', '', '', '');
INSERT INTO `vorstand` VALUES('35', 'list', 'Peter Krenmayr', 'Ligagremium', '', '', '');
INSERT INTO `vorstand` VALUES('36', 'list', 'Andreas Rabel ', 'Ligaausschuss', '', '', '');
INSERT INTO `vorstand` VALUES('37', 'list', 'Harald Starl ', 'Ligaausschuss', '', '', '');
INSERT INTO `vorstand` VALUES('38', 'list', 'Karl Pröll ', 'Ligaausschuss', '', '', '');
INSERT INTO `vorstand` VALUES('39', 'list', 'Hermann Schausberger', 'Ligaausschuss', '', '', '');
INSERT INTO `vorstand` VALUES('40', 'list', 'Markus Eckersberger ', 'Ligaausschuss', '', '', '');
INSERT INTO `vorstand` VALUES('41', 'list', 'Michael Kaun ', 'Ligaausschuss', '', '', '');
INSERT INTO `vorstand` VALUES('42', 'list', 'Klaus Mitterhauser', 'Ligaausschuss', '', '', '');
INSERT INTO `vorstand` VALUES('43', 'list', 'Sandra Kranzl ', 'Schiedsgericht', '', '', '');
INSERT INTO `vorstand` VALUES('44', 'list', 'Wolfgang Hofreiter ', 'Schiedsgericht', '', '', '');
INSERT INTO `vorstand` VALUES('45', 'list', 'Manfred Berger-Söllinger', 'Schiedsgericht', '', '', '');
INSERT INTO `vorstand` VALUES('46', 'list', 'Christian Klement ', 'Schiedsgericht', '', '', '');
INSERT INTO `vorstand` VALUES('47', 'list', 'Franz Gösweiner', 'Schiedsgericht', '', '', '');
INSERT INTO `vorstand` VALUES('48', 'list', 'Martin Grafinger', 'Schiedsgericht', '', '', '');
INSERT INTO `vorstand` VALUES('49', 'list', 'Richard Zöllner', 'Schiedsgericht', '', '', '');
INSERT INTO `vorstand` VALUES('50', 'list', 'Stefan Holl', 'Schiedsgericht', '', '', '');
